language: "ruby"

after_install: "bundle exec rake appraisal:install"
before_script: "bundle exec rake db:build_databases db:create_tables"
script:        "bundle exec rake spec"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree

gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile

notifications:
  recipients:
    - gaffneyc@gmail.com
